apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tesbo.fullname" . }}-env
  labels:
    {{- include "tesbo.labels" . | nindent 4 }}
type: Opaque
stringData:
  INTERNAL_SHARED_TOKEN: {{ required "secrets.internalToken is required (run `tesbo-grid init` or `openssl rand -hex 32`)" .Values.secrets.internalToken | quote }}
  EXECUTION_API_SHARED_TOKEN: {{ .Values.secrets.internalToken | quote }}
  BACKEND_DATABASE_URL: {{ include "tesbo.databaseUrl" . | quote }}
  EXECUTION_DATABASE_URL: {{ include "tesbo.executionDatabaseUrl" . | quote }}
  REDIS_URL: {{ include "tesbo.redisUrl" . | quote }}
  REDIS_ADDRESS: {{ .Values.redis.kedaAddress | default (printf "%s-redis:6379" (include "tesbo.fullname" .)) | quote }}
  REDIS_PASSWORD: {{ .Values.redis.kedaPassword | quote }}
  ARTIFACT_STORAGE_PROVIDER: {{ .Values.storage.provider | quote }}
  S3_ENDPOINT: {{ .Values.storage.endpoint | quote }}
  S3_REGION: {{ .Values.storage.region | quote }}
  S3_BUCKET: {{ .Values.storage.bucket | quote }}
  S3_ACCESS_KEY: {{ .Values.storage.accessKey | quote }}
  S3_SECRET_KEY: {{ .Values.storage.secretKey | quote }}
  S3_PUBLIC_BASE_URL: {{ .Values.storage.publicBaseUrl | quote }}
  S3_FORCE_PATH_STYLE: {{ .Values.storage.forcePathStyle | quote }}
