// `tesbo-grid init` — interactive (or flag-driven) config generator.
//
// Produces, in the repo root:
//   - compose target:   .env            (consumed by docker-compose.yml)
//   - kubernetes target: values.generated.yaml (Helm values for deploy/helm/tesbo-grid)
//
// Strong secrets (internal token, Postgres password) are auto-generated.
import fs from "node:fs";
import path from "node:path";
import {
  ask, choose, confirm, randomSecret, findRepoRoot,
  heading, info, ok, warn, step,
} from "./util.js";

function parseFlags(argv) {
  const flags = {};
  for (let i = 0; i < argv.length; i += 1) {
    if (argv[i].startsWith("--")) {
      const key = argv[i].slice(2);
      const val = argv[i + 1] && !argv[i + 1].startsWith("--") ? argv[(i += 1)] : "true";
      flags[key] = val;
    }
  }
  return flags;
}

function renderEnv(cfg) {
  return `# Generated by \`tesbo-grid init\` — safe to edit by hand.
TESBO_REGISTRY=${cfg.registry}
TESBO_IMAGE_TAG=${cfg.imageTag}

FRONTEND_URL=${cfg.frontendUrl}
BACKEND_PUBLIC_URL=${cfg.backendUrl}
RUNNER_PUBLIC_API_URL=${cfg.runnerUrl}
SELENIUM_GRID_DOMAIN=${cfg.gridDomain}

TESBO_INTERNAL_TOKEN=${cfg.internalToken}
POSTGRES_PASSWORD=${cfg.postgresPassword}

ARTIFACT_STORAGE_PROVIDER=${cfg.storageProvider}
S3_ENDPOINT=${cfg.s3Endpoint}
S3_REGION=${cfg.s3Region}
S3_BUCKET=${cfg.s3Bucket}
S3_ACCESS_KEY=${cfg.s3AccessKey}
S3_SECRET_KEY=${cfg.s3SecretKey}
S3_PUBLIC_BASE_URL=${cfg.s3PublicBaseUrl}
S3_FORCE_PATH_STYLE=${cfg.s3ForcePathStyle}

PLAYWRIGHT_JS_CONCURRENCY=${cfg.jsConcurrency}
PLAYWRIGHT_OTHER_CONCURRENCY=${cfg.otherConcurrency}
SELENIUM_NODE_MAX_SESSIONS=${cfg.nodeMaxSessions}

MW_APM_ACCESS_TOKEN=
MW_AGENT_SERVICE=172.17.0.1
`;
}

function renderValues(cfg) {
  return `# Generated by \`tesbo-grid init\` — Helm values for deploy/helm/tesbo-grid.
image:
  registry: ${cfg.registry}
  tag: ${cfg.imageTag}

domains:
  frontend: ${cfg.frontendHost}
  backend: ${cfg.backendHost}
  runner: ${cfg.runnerHost}
  seleniumGrid: ${cfg.gridDomain}

ingress:
  provider: ${cfg.ingressProvider}   # aws | gcp | azure | generic-ingress | none

secrets:
  internalToken: "${cfg.internalToken}"

database:
  url: "${cfg.databaseUrl}"

redis:
  url: "${cfg.redisUrl}"

storage:
  provider: ${cfg.storageProvider}
  endpoint: "${cfg.s3Endpoint}"
  region: ${cfg.s3Region}
  bucket: "${cfg.s3Bucket}"
  accessKey: "${cfg.s3AccessKey}"
  secretKey: "${cfg.s3SecretKey}"
  publicBaseUrl: "${cfg.s3PublicBaseUrl}"
  forcePathStyle: ${cfg.s3ForcePathStyle}

autoscaling:
  enabled: ${cfg.kedaEnabled}
`;
}

export async function init(argv) {
  const flags = parseFlags(argv);
  const interactive = flags["non-interactive"] !== "true" && flags.yes !== "true";
  const repoRoot = findRepoRoot();

  heading("Tesbo-Grid setup");
  info(`Repo root: ${repoRoot}`);

  const target = flags.target ||
    (interactive
      ? await choose("Where do you want to deploy?", [
          { label: "Docker Compose (single VM — easiest)", value: "compose" },
          { label: "Kubernetes via Helm (EKS/GKE/AKS)", value: "kubernetes" },
        ], 0)
      : "compose");

  const cfg = {
    registry: flags.registry || "ghcr.io/qablehq/tesbo-grid",
    imageTag: flags["image-tag"] || "latest",
    internalToken: flags["internal-token"] || randomSecret(32),
    postgresPassword: flags["postgres-password"] || randomSecret(16),
    storageProvider: flags["storage-provider"] || "none",
    s3Endpoint: flags["s3-endpoint"] || "",
    s3Region: flags["s3-region"] || "us-east-1",
    s3Bucket: flags["s3-bucket"] || "",
    s3AccessKey: flags["s3-access-key"] || "",
    s3SecretKey: flags["s3-secret-key"] || "",
    s3PublicBaseUrl: flags["s3-public-base-url"] || "",
    s3ForcePathStyle: flags["s3-force-path-style"] || "false",
    jsConcurrency: flags["js-concurrency"] || "20",
    otherConcurrency: flags["other-concurrency"] || "5",
    nodeMaxSessions: flags["node-max-sessions"] || "4",
  };

  if (target === "compose") {
    cfg.frontendUrl = flags["frontend-url"] ||
      (interactive ? await ask("Dashboard URL", "http://localhost:3100") : "http://localhost:3100");
    cfg.backendUrl = flags["backend-url"] ||
      (interactive ? await ask("Backend API URL", "http://localhost:7100") : "http://localhost:7100");
    cfg.runnerUrl = flags["runner-url"] ||
      (interactive ? await ask("Runner API URL", "http://localhost:7420") : "http://localhost:7420");
    cfg.gridDomain = flags["grid-domain"] ||
      (interactive ? await ask("Selenium Grid domain", "localhost:4444") : "localhost:4444");

    if (interactive && cfg.storageProvider === "none") {
      const useS3 = await confirm("Configure S3-compatible artifact storage now?", false);
      if (useS3) {
        cfg.storageProvider = "s3";
        cfg.s3Endpoint = await ask("S3 endpoint (blank for AWS S3)", "");
        cfg.s3Region = await ask("S3 region", "us-east-1");
        cfg.s3Bucket = await ask("S3 bucket", "");
        cfg.s3AccessKey = await ask("S3 access key", "");
        cfg.s3SecretKey = await ask("S3 secret key", "");
      }
    }

    const outPath = path.join(repoRoot, ".env");
    if (fs.existsSync(outPath) && interactive) {
      const overwrite = await confirm(`${outPath} exists. Overwrite?`, false);
      if (!overwrite) {
        warn("Aborted — existing .env kept.");
        return 0;
      }
    }
    fs.writeFileSync(outPath, renderEnv(cfg), { mode: 0o600 });
    ok(`Wrote ${outPath}`);
    heading("Next steps");
    info("  tesbo-grid doctor      # verify prerequisites");
    info("  tesbo-grid up          # build + start the stack");
    return 0;
  }

  // kubernetes target
  cfg.frontendHost = flags["frontend-host"] ||
    (interactive ? await ask("Dashboard hostname", "grid.example.com") : "grid.example.com");
  cfg.backendHost = flags["backend-host"] ||
    (interactive ? await ask("Backend API hostname", "api.example.com") : "api.example.com");
  cfg.runnerHost = flags["runner-host"] ||
    (interactive ? await ask("Runner API hostname", "run.example.com") : "run.example.com");
  cfg.gridDomain = flags["grid-domain"] ||
    (interactive ? await ask("Selenium Grid hostname", "selenium.example.com") : "selenium.example.com");
  cfg.ingressProvider = flags["ingress-provider"] ||
    (interactive ? await choose("Load balancer / ingress provider?", [
      { label: "Generic Ingress (nginx, etc.)", value: "generic-ingress" },
      { label: "AWS (ELB)", value: "aws" },
      { label: "GCP (GCLB)", value: "gcp" },
      { label: "Azure (ALB)", value: "azure" },
    ], 0) : "generic-ingress");
  cfg.databaseUrl = flags["database-url"] ||
    (interactive ? await ask("Postgres URL (managed DB recommended)", "") : "");
  cfg.redisUrl = flags["redis-url"] ||
    (interactive ? await ask("Redis URL (managed recommended)", "") : "");
  cfg.kedaEnabled = flags["keda-enabled"] ||
    (interactive ? (await confirm("Enable KEDA autoscaling? (requires KEDA installed)", true) ? "true" : "false") : "true");

  const outPath = path.join(repoRoot, "values.generated.yaml");
  fs.writeFileSync(outPath, renderValues(cfg), { mode: 0o600 });
  ok(`Wrote ${outPath}`);
  heading("Next steps");
  step("Review values.generated.yaml (set database/redis URLs if blank).");
  info("  tesbo-grid doctor --target kubernetes");
  info("  tesbo-grid up --target kubernetes");
  return 0;
}
