#!/usr/bin/env bash
# One-command local dev stack for TesboGrid.
#
#   ./scripts/dev-local.sh           # start everything
#   ./scripts/dev-local.sh --reset   # wipe local Postgres volume, then start
#   ./scripts/dev-local.sh --down    # stop & remove local Postgres container
#
# What runs locally:
#   - Postgres 16 in Docker        (container: tesbo-grid-local-db, host port 5434)
#   - grid-backend  (npm run dev)  (http://localhost:7100)
#   - grid-frontend (npm run dev)  (http://localhost:3100)
#
# What stays in the cloud:
#   - grid-runner-api + workers + Selenium grid (set EXECUTION_API_URL below)
#
# Re-runs are idempotent: the Postgres volume persists between invocations so
# your local data is preserved. Use --reset to start from a blank DB.

set -euo pipefail

# Resolve repo root (parent of this script's directory).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

# ── Config ──────────────────────────────────────────────────────────────────
DB_CONTAINER="tesbo-grid-local-db"
DB_VOLUME="tesbo-grid-local-pgdata"
DB_PORT="5434"
DB_USER="postgres"
DB_PASS="postgres"
DB_NAME="tesbo_grid_local"

BACKEND_PORT="7100"
FRONTEND_PORT="3100"

# Cloud runner-api the local backend will dispatch runs to.
# Override by exporting EXECUTION_API_URL before invoking the script.
DEFAULT_EXECUTION_API_URL="${EXECUTION_API_URL:-https://run.tesbogrid.com}"

LOG_DIR="$REPO_ROOT/.dev-logs"
mkdir -p "$LOG_DIR"

# ── Pretty output ───────────────────────────────────────────────────────────
say()  { printf "\033[1;36m▸\033[0m %s\n" "$*"; }
ok()   { printf "\033[1;32m✓\033[0m %s\n" "$*"; }
warn() { printf "\033[1;33m!\033[0m %s\n" "$*"; }
die()  { printf "\033[1;31m✗\033[0m %s\n" "$*" >&2; exit 1; }

# ── Subcommands ─────────────────────────────────────────────────────────────
case "${1:-}" in
  --down)
    say "Stopping local Postgres ($DB_CONTAINER)"
    docker rm -f "$DB_CONTAINER" >/dev/null 2>&1 || true
    ok  "Stopped. Volume '$DB_VOLUME' preserved (use --reset to wipe)."
    exit 0
    ;;
  --reset)
    say "Wiping local Postgres container + volume"
    docker rm -f "$DB_CONTAINER" >/dev/null 2>&1 || true
    docker volume rm "$DB_VOLUME" >/dev/null 2>&1 || true
    ok  "Reset complete. Continuing with fresh DB…"
    ;;
  -h|--help)
    sed -n '1,20p' "$0" | sed 's/^# \{0,1\}//'
    exit 0
    ;;
esac

# ── Prereqs ─────────────────────────────────────────────────────────────────
command -v docker >/dev/null 2>&1 || die "Docker is required. Install Docker Desktop and retry."
command -v node   >/dev/null 2>&1 || die "Node.js is required."
command -v npm    >/dev/null 2>&1 || die "npm is required."
docker info >/dev/null 2>&1 || die "Docker daemon is not running. Start Docker Desktop and retry."

# ── Local Postgres ──────────────────────────────────────────────────────────
if docker ps -a --format '{{.Names}}' | grep -qx "$DB_CONTAINER"; then
  if ! docker ps --format '{{.Names}}' | grep -qx "$DB_CONTAINER"; then
    say "Starting existing Postgres container"
    docker start "$DB_CONTAINER" >/dev/null
  else
    ok "Postgres container already running"
  fi
else
  say "Launching Postgres 16 ($DB_CONTAINER) on :$DB_PORT"
  docker run -d \
    --name "$DB_CONTAINER" \
    -e POSTGRES_USER="$DB_USER" \
    -e POSTGRES_PASSWORD="$DB_PASS" \
    -e POSTGRES_DB="$DB_NAME" \
    -p "$DB_PORT:5432" \
    -v "$DB_VOLUME:/var/lib/postgresql/data" \
    postgres:16-alpine >/dev/null
fi

# Wait for readiness.
say "Waiting for Postgres to accept connections"
for i in {1..30}; do
  if docker exec "$DB_CONTAINER" pg_isready -U "$DB_USER" >/dev/null 2>&1; then
    ok "Postgres ready"
    break
  fi
  sleep 1
  [[ $i -eq 30 ]] && die "Postgres did not become ready within 30s"
done

DATABASE_URL="postgresql://${DB_USER}:${DB_PASS}@localhost:${DB_PORT}/${DB_NAME}"

# ── .env files (only created when missing — never overwrite user edits) ─────
BACKEND_ENV="$REPO_ROOT/grid-backend/.env"
if [[ ! -f "$BACKEND_ENV" ]]; then
  say "Writing $BACKEND_ENV"
  cat > "$BACKEND_ENV" <<EOF
# Local dev — generated by scripts/dev-local.sh. Safe to edit.
PORT=$BACKEND_PORT
NODE_ENV=development

DATABASE_URL=$DATABASE_URL

FRONTEND_URL=http://localhost:$FRONTEND_PORT
CORS_ALLOWED_ORIGINS=http://localhost:$FRONTEND_PORT
PUBLIC_BACKEND_URL=http://localhost:$BACKEND_PORT

# Cloud runner-api (where job dispatches go).
EXECUTION_API_URL=$DEFAULT_EXECUTION_API_URL
EXECUTION_API_SHARED_TOKEN=

# Optional integrations — leave blank to disable.
POSTMARK_API_TOKEN=
GH_APP_ID=
GH_APP_NAME=
GH_APP_CLIENT_ID=
GH_APP_CLIENT_SECRET=
GH_APP_PRIVATE_KEY=
GH_APP_WEBHOOK_SECRET=
STRIPE_SECRET_KEY=
STRIPE_WEBHOOK_SECRET=
EOF
  ok "Backend .env created"
else
  ok "Backend .env exists — leaving alone"
fi

FRONTEND_ENV="$REPO_ROOT/grid-frontend/.env.local"
if [[ ! -f "$FRONTEND_ENV" ]]; then
  say "Writing $FRONTEND_ENV"
  cat > "$FRONTEND_ENV" <<EOF
# Local dev — generated by scripts/dev-local.sh. Safe to edit.
NEXT_PUBLIC_API_URL=http://localhost:$BACKEND_PORT
EOF
  ok "Frontend .env.local created"
else
  ok "Frontend .env.local exists — leaving alone"
fi

# ── npm install (only if node_modules missing) ──────────────────────────────
if [[ ! -d "$REPO_ROOT/node_modules" ]]; then
  say "Installing workspace dependencies (npm install)"
  npm install
else
  ok "node_modules present — skipping install"
fi

# ── Migrations ──────────────────────────────────────────────────────────────
say "Running grid-backend migrations against local DB"
( cd "$REPO_ROOT/grid-backend" && DATABASE_URL="$DATABASE_URL" npm run migrate )
ok "Migrations applied"

# ── Start backend + frontend ────────────────────────────────────────────────
PIDS=()

cleanup() {
  echo
  say "Shutting down dev processes"
  for pid in "${PIDS[@]:-}"; do
    [[ -n "${pid:-}" ]] && kill "$pid" 2>/dev/null || true
  done
  # Give them a moment to exit cleanly.
  sleep 1
  for pid in "${PIDS[@]:-}"; do
    [[ -n "${pid:-}" ]] && kill -9 "$pid" 2>/dev/null || true
  done
  ok "Dev processes stopped. Local Postgres is still running — './scripts/dev-local.sh --down' to stop it."
}
trap cleanup EXIT INT TERM

say "Starting grid-backend  → http://localhost:$BACKEND_PORT  (log: $LOG_DIR/backend.log)"
( npm run dev:backend ) > "$LOG_DIR/backend.log" 2>&1 &
PIDS+=($!)

say "Starting grid-frontend → http://localhost:$FRONTEND_PORT  (log: $LOG_DIR/frontend.log)"
( npm run dev:frontend ) > "$LOG_DIR/frontend.log" 2>&1 &
PIDS+=($!)

# Banner.
cat <<EOF

────────────────────────────────────────────────────────────
  TesboGrid local dev stack is up
────────────────────────────────────────────────────────────
  Frontend     http://localhost:$FRONTEND_PORT
  Backend      http://localhost:$BACKEND_PORT
  Postgres     localhost:$DB_PORT  (user=$DB_USER, db=$DB_NAME)
  Runner API   $DEFAULT_EXECUTION_API_URL  (cloud)

  Tailing logs below — Ctrl+C to stop frontend + backend.
  Postgres keeps running across restarts; --down to stop it,
  --reset to wipe its volume.
────────────────────────────────────────────────────────────

EOF

# Tail both logs side-by-side until the user kills the script.
tail -F "$LOG_DIR/backend.log" "$LOG_DIR/frontend.log"
